# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 976707e2ec2fd72143c560db9e7d3973d85a1abb4355f46efec9186c4c9948c0d8928075b73296aabf549efdfdc125395796b626b3091c4f9e8cd81a84f86514

test:
  secret_key_base: 431316dcd640276d680ffaa844f98b412d8a5b4cfdcaa04cb89f4498fd97a0728d1074a71f5929e2864168887b023c9bdc74a237f9d5686b32644eb3b8e5663c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
